/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardProtectedRouteRouteImport } from './routes/dashboard/_protected/route'
import { Route as DashboardProtectedIndexRouteImport } from './routes/dashboard/_protected/index'
import { Route as DashboardProtectedPeriodsIndexRouteImport } from './routes/dashboard/_protected/periods/index'
import { Route as DashboardProtectedPeriodsCreateRouteImport } from './routes/dashboard/_protected/periods/create'
import { Route as DashboardProtectedPeriodsLayoutRouteImport } from './routes/dashboard/_protected/periods/_layout'
import { Route as DashboardProtectedPeriodsPeriodIdIndexRouteImport } from './routes/dashboard/_protected/periods/$periodId/index'
import { Route as DashboardProtectedPeriodsPeriodIdSettingsRouteImport } from './routes/dashboard/_protected/periods/$periodId/settings'
import { Route as DashboardProtectedPeriodsPeriodIdLayoutRouteImport } from './routes/dashboard/_protected/periods/$periodId/_layout'
import { Route as DashboardProtectedPeriodsPeriodIdTasksIndexRouteImport } from './routes/dashboard/_protected/periods/$periodId/tasks/index'
import { Route as DashboardProtectedPeriodsPeriodIdSubjectsIndexRouteImport } from './routes/dashboard/_protected/periods/$periodId/subjects/index'
import { Route as DashboardProtectedPeriodsPeriodIdTasksKanbanRouteImport } from './routes/dashboard/_protected/periods/$periodId/tasks/kanban'
import { Route as DashboardProtectedPeriodsPeriodIdTasksCreateRouteImport } from './routes/dashboard/_protected/periods/$periodId/tasks/create'
import { Route as DashboardProtectedPeriodsPeriodIdTasksLayoutRouteImport } from './routes/dashboard/_protected/periods/$periodId/tasks/_layout'
import { Route as DashboardProtectedPeriodsPeriodIdTasksTaskIdRouteImport } from './routes/dashboard/_protected/periods/$periodId/tasks/$taskId'
import { Route as DashboardProtectedPeriodsPeriodIdSubjectsCreateRouteImport } from './routes/dashboard/_protected/periods/$periodId/subjects/create'
import { Route as DashboardProtectedPeriodsPeriodIdSubjectsLayoutRouteImport } from './routes/dashboard/_protected/periods/$periodId/subjects/_layout'
import { Route as DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRouteImport } from './routes/dashboard/_protected/periods/$periodId/subjects/$subjectId'
import { Route as DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdIndexRouteImport } from './routes/dashboard/_protected/periods/$periodId/subjects/$subjectId/index'
import { Route as DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdTasksRouteImport } from './routes/dashboard/_protected/periods/$periodId/subjects/$subjectId/tasks'

const DashboardRouteImport = createFileRoute('/dashboard')()
const DashboardProtectedPeriodsRouteImport = createFileRoute(
  '/dashboard/_protected/periods',
)()
const DashboardProtectedPeriodsPeriodIdRouteImport = createFileRoute(
  '/dashboard/_protected/periods/$periodId',
)()
const DashboardProtectedPeriodsPeriodIdTasksRouteImport = createFileRoute(
  '/dashboard/_protected/periods/$periodId/tasks',
)()
const DashboardProtectedPeriodsPeriodIdSubjectsRouteImport = createFileRoute(
  '/dashboard/_protected/periods/$periodId/subjects',
)()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProtectedRouteRoute = DashboardProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProtectedPeriodsRoute =
  DashboardProtectedPeriodsRouteImport.update({
    id: '/periods',
    path: '/periods',
    getParentRoute: () => DashboardProtectedRouteRoute,
  } as any)
const DashboardProtectedIndexRoute = DashboardProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProtectedRouteRoute,
} as any)
const DashboardProtectedPeriodsPeriodIdRoute =
  DashboardProtectedPeriodsPeriodIdRouteImport.update({
    id: '/$periodId',
    path: '/$periodId',
    getParentRoute: () => DashboardProtectedPeriodsRoute,
  } as any)
const DashboardProtectedPeriodsIndexRoute =
  DashboardProtectedPeriodsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProtectedPeriodsRoute,
  } as any)
const DashboardProtectedPeriodsCreateRoute =
  DashboardProtectedPeriodsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardProtectedPeriodsRoute,
  } as any)
const DashboardProtectedPeriodsLayoutRoute =
  DashboardProtectedPeriodsLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => DashboardProtectedPeriodsRoute,
  } as any)
const DashboardProtectedPeriodsPeriodIdTasksRoute =
  DashboardProtectedPeriodsPeriodIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => DashboardProtectedPeriodsPeriodIdRoute,
  } as any)
const DashboardProtectedPeriodsPeriodIdSubjectsRoute =
  DashboardProtectedPeriodsPeriodIdSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => DashboardProtectedPeriodsPeriodIdRoute,
  } as any)
const DashboardProtectedPeriodsPeriodIdIndexRoute =
  DashboardProtectedPeriodsPeriodIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProtectedPeriodsPeriodIdRoute,
  } as any)
const DashboardProtectedPeriodsPeriodIdSettingsRoute =
  DashboardProtectedPeriodsPeriodIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProtectedPeriodsPeriodIdRoute,
  } as any)
const DashboardProtectedPeriodsPeriodIdLayoutRoute =
  DashboardProtectedPeriodsPeriodIdLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => DashboardProtectedPeriodsPeriodIdRoute,
  } as any)
const DashboardProtectedPeriodsPeriodIdTasksIndexRoute =
  DashboardProtectedPeriodsPeriodIdTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProtectedPeriodsPeriodIdTasksRoute,
  } as any)
const DashboardProtectedPeriodsPeriodIdSubjectsIndexRoute =
  DashboardProtectedPeriodsPeriodIdSubjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProtectedPeriodsPeriodIdSubjectsRoute,
  } as any)
const DashboardProtectedPeriodsPeriodIdTasksKanbanRoute =
  DashboardProtectedPeriodsPeriodIdTasksKanbanRouteImport.update({
    id: '/kanban',
    path: '/kanban',
    getParentRoute: () => DashboardProtectedPeriodsPeriodIdTasksRoute,
  } as any)
const DashboardProtectedPeriodsPeriodIdTasksCreateRoute =
  DashboardProtectedPeriodsPeriodIdTasksCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardProtectedPeriodsPeriodIdTasksRoute,
  } as any)
const DashboardProtectedPeriodsPeriodIdTasksLayoutRoute =
  DashboardProtectedPeriodsPeriodIdTasksLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => DashboardProtectedPeriodsPeriodIdTasksRoute,
  } as any)
const DashboardProtectedPeriodsPeriodIdTasksTaskIdRoute =
  DashboardProtectedPeriodsPeriodIdTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => DashboardProtectedPeriodsPeriodIdRoute,
  } as any)
const DashboardProtectedPeriodsPeriodIdSubjectsCreateRoute =
  DashboardProtectedPeriodsPeriodIdSubjectsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardProtectedPeriodsPeriodIdSubjectsRoute,
  } as any)
const DashboardProtectedPeriodsPeriodIdSubjectsLayoutRoute =
  DashboardProtectedPeriodsPeriodIdSubjectsLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => DashboardProtectedPeriodsPeriodIdSubjectsRoute,
  } as any)
const DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRoute =
  DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRouteImport.update({
    id: '/subjects/$subjectId',
    path: '/subjects/$subjectId',
    getParentRoute: () => DashboardProtectedPeriodsPeriodIdRoute,
  } as any)
const DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdIndexRoute =
  DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRoute,
  } as any)
const DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdTasksRoute =
  DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () =>
      DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardProtectedRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/': typeof DashboardProtectedIndexRoute
  '/dashboard/periods': typeof DashboardProtectedPeriodsLayoutRoute
  '/dashboard/periods/create': typeof DashboardProtectedPeriodsCreateRoute
  '/dashboard/periods/': typeof DashboardProtectedPeriodsIndexRoute
  '/dashboard/periods/$periodId': typeof DashboardProtectedPeriodsPeriodIdLayoutRoute
  '/dashboard/periods/$periodId/settings': typeof DashboardProtectedPeriodsPeriodIdSettingsRoute
  '/dashboard/periods/$periodId/': typeof DashboardProtectedPeriodsPeriodIdIndexRoute
  '/dashboard/periods/$periodId/subjects/$subjectId': typeof DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRouteWithChildren
  '/dashboard/periods/$periodId/subjects': typeof DashboardProtectedPeriodsPeriodIdSubjectsLayoutRoute
  '/dashboard/periods/$periodId/subjects/create': typeof DashboardProtectedPeriodsPeriodIdSubjectsCreateRoute
  '/dashboard/periods/$periodId/tasks/$taskId': typeof DashboardProtectedPeriodsPeriodIdTasksTaskIdRoute
  '/dashboard/periods/$periodId/tasks': typeof DashboardProtectedPeriodsPeriodIdTasksLayoutRoute
  '/dashboard/periods/$periodId/tasks/create': typeof DashboardProtectedPeriodsPeriodIdTasksCreateRoute
  '/dashboard/periods/$periodId/tasks/kanban': typeof DashboardProtectedPeriodsPeriodIdTasksKanbanRoute
  '/dashboard/periods/$periodId/subjects/': typeof DashboardProtectedPeriodsPeriodIdSubjectsIndexRoute
  '/dashboard/periods/$periodId/tasks/': typeof DashboardProtectedPeriodsPeriodIdTasksIndexRoute
  '/dashboard/periods/$periodId/subjects/$subjectId/tasks': typeof DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdTasksRoute
  '/dashboard/periods/$periodId/subjects/$subjectId/': typeof DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardProtectedIndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/periods': typeof DashboardProtectedPeriodsIndexRoute
  '/dashboard/periods/create': typeof DashboardProtectedPeriodsCreateRoute
  '/dashboard/periods/$periodId': typeof DashboardProtectedPeriodsPeriodIdIndexRoute
  '/dashboard/periods/$periodId/settings': typeof DashboardProtectedPeriodsPeriodIdSettingsRoute
  '/dashboard/periods/$periodId/subjects': typeof DashboardProtectedPeriodsPeriodIdSubjectsIndexRoute
  '/dashboard/periods/$periodId/subjects/create': typeof DashboardProtectedPeriodsPeriodIdSubjectsCreateRoute
  '/dashboard/periods/$periodId/tasks/$taskId': typeof DashboardProtectedPeriodsPeriodIdTasksTaskIdRoute
  '/dashboard/periods/$periodId/tasks': typeof DashboardProtectedPeriodsPeriodIdTasksIndexRoute
  '/dashboard/periods/$periodId/tasks/create': typeof DashboardProtectedPeriodsPeriodIdTasksCreateRoute
  '/dashboard/periods/$periodId/tasks/kanban': typeof DashboardProtectedPeriodsPeriodIdTasksKanbanRoute
  '/dashboard/periods/$periodId/subjects/$subjectId/tasks': typeof DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdTasksRoute
  '/dashboard/periods/$periodId/subjects/$subjectId': typeof DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_layout': typeof LayoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_protected': typeof DashboardProtectedRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/_protected/': typeof DashboardProtectedIndexRoute
  '/dashboard/_protected/periods': typeof DashboardProtectedPeriodsRouteWithChildren
  '/dashboard/_protected/periods/_layout': typeof DashboardProtectedPeriodsLayoutRoute
  '/dashboard/_protected/periods/create': typeof DashboardProtectedPeriodsCreateRoute
  '/dashboard/_protected/periods/': typeof DashboardProtectedPeriodsIndexRoute
  '/dashboard/_protected/periods/$periodId': typeof DashboardProtectedPeriodsPeriodIdRouteWithChildren
  '/dashboard/_protected/periods/$periodId/_layout': typeof DashboardProtectedPeriodsPeriodIdLayoutRoute
  '/dashboard/_protected/periods/$periodId/settings': typeof DashboardProtectedPeriodsPeriodIdSettingsRoute
  '/dashboard/_protected/periods/$periodId/': typeof DashboardProtectedPeriodsPeriodIdIndexRoute
  '/dashboard/_protected/periods/$periodId/subjects/$subjectId': typeof DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRouteWithChildren
  '/dashboard/_protected/periods/$periodId/subjects': typeof DashboardProtectedPeriodsPeriodIdSubjectsRouteWithChildren
  '/dashboard/_protected/periods/$periodId/subjects/_layout': typeof DashboardProtectedPeriodsPeriodIdSubjectsLayoutRoute
  '/dashboard/_protected/periods/$periodId/subjects/create': typeof DashboardProtectedPeriodsPeriodIdSubjectsCreateRoute
  '/dashboard/_protected/periods/$periodId/tasks/$taskId': typeof DashboardProtectedPeriodsPeriodIdTasksTaskIdRoute
  '/dashboard/_protected/periods/$periodId/tasks': typeof DashboardProtectedPeriodsPeriodIdTasksRouteWithChildren
  '/dashboard/_protected/periods/$periodId/tasks/_layout': typeof DashboardProtectedPeriodsPeriodIdTasksLayoutRoute
  '/dashboard/_protected/periods/$periodId/tasks/create': typeof DashboardProtectedPeriodsPeriodIdTasksCreateRoute
  '/dashboard/_protected/periods/$periodId/tasks/kanban': typeof DashboardProtectedPeriodsPeriodIdTasksKanbanRoute
  '/dashboard/_protected/periods/$periodId/subjects/': typeof DashboardProtectedPeriodsPeriodIdSubjectsIndexRoute
  '/dashboard/_protected/periods/$periodId/tasks/': typeof DashboardProtectedPeriodsPeriodIdTasksIndexRoute
  '/dashboard/_protected/periods/$periodId/subjects/$subjectId/tasks': typeof DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdTasksRoute
  '/dashboard/_protected/periods/$periodId/subjects/$subjectId/': typeof DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/login'
    | '/dashboard/'
    | '/dashboard/periods'
    | '/dashboard/periods/create'
    | '/dashboard/periods/'
    | '/dashboard/periods/$periodId'
    | '/dashboard/periods/$periodId/settings'
    | '/dashboard/periods/$periodId/'
    | '/dashboard/periods/$periodId/subjects/$subjectId'
    | '/dashboard/periods/$periodId/subjects'
    | '/dashboard/periods/$periodId/subjects/create'
    | '/dashboard/periods/$periodId/tasks/$taskId'
    | '/dashboard/periods/$periodId/tasks'
    | '/dashboard/periods/$periodId/tasks/create'
    | '/dashboard/periods/$periodId/tasks/kanban'
    | '/dashboard/periods/$periodId/subjects/'
    | '/dashboard/periods/$periodId/tasks/'
    | '/dashboard/periods/$periodId/subjects/$subjectId/tasks'
    | '/dashboard/periods/$periodId/subjects/$subjectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/login'
    | '/dashboard/periods'
    | '/dashboard/periods/create'
    | '/dashboard/periods/$periodId'
    | '/dashboard/periods/$periodId/settings'
    | '/dashboard/periods/$periodId/subjects'
    | '/dashboard/periods/$periodId/subjects/create'
    | '/dashboard/periods/$periodId/tasks/$taskId'
    | '/dashboard/periods/$periodId/tasks'
    | '/dashboard/periods/$periodId/tasks/create'
    | '/dashboard/periods/$periodId/tasks/kanban'
    | '/dashboard/periods/$periodId/subjects/$subjectId/tasks'
    | '/dashboard/periods/$periodId/subjects/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/_layout'
    | '/dashboard'
    | '/dashboard/_protected'
    | '/auth/callback'
    | '/auth/login'
    | '/dashboard/_protected/'
    | '/dashboard/_protected/periods'
    | '/dashboard/_protected/periods/_layout'
    | '/dashboard/_protected/periods/create'
    | '/dashboard/_protected/periods/'
    | '/dashboard/_protected/periods/$periodId'
    | '/dashboard/_protected/periods/$periodId/_layout'
    | '/dashboard/_protected/periods/$periodId/settings'
    | '/dashboard/_protected/periods/$periodId/'
    | '/dashboard/_protected/periods/$periodId/subjects/$subjectId'
    | '/dashboard/_protected/periods/$periodId/subjects'
    | '/dashboard/_protected/periods/$periodId/subjects/_layout'
    | '/dashboard/_protected/periods/$periodId/subjects/create'
    | '/dashboard/_protected/periods/$periodId/tasks/$taskId'
    | '/dashboard/_protected/periods/$periodId/tasks'
    | '/dashboard/_protected/periods/$periodId/tasks/_layout'
    | '/dashboard/_protected/periods/$periodId/tasks/create'
    | '/dashboard/_protected/periods/$periodId/tasks/kanban'
    | '/dashboard/_protected/periods/$periodId/subjects/'
    | '/dashboard/_protected/periods/$periodId/tasks/'
    | '/dashboard/_protected/periods/$periodId/subjects/$subjectId/tasks'
    | '/dashboard/_protected/periods/$periodId/subjects/$subjectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  LayoutRoute: typeof LayoutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_protected': {
      id: '/dashboard/_protected'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardProtectedRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/_protected/periods': {
      id: '/dashboard/_protected/periods'
      path: '/periods'
      fullPath: '/dashboard/periods'
      preLoaderRoute: typeof DashboardProtectedPeriodsRouteImport
      parentRoute: typeof DashboardProtectedRouteRoute
    }
    '/dashboard/_protected/': {
      id: '/dashboard/_protected/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardProtectedIndexRouteImport
      parentRoute: typeof DashboardProtectedRouteRoute
    }
    '/dashboard/_protected/periods/$periodId': {
      id: '/dashboard/_protected/periods/$periodId'
      path: '/$periodId'
      fullPath: '/dashboard/periods/$periodId'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdRouteImport
      parentRoute: typeof DashboardProtectedPeriodsRoute
    }
    '/dashboard/_protected/periods/': {
      id: '/dashboard/_protected/periods/'
      path: '/'
      fullPath: '/dashboard/periods/'
      preLoaderRoute: typeof DashboardProtectedPeriodsIndexRouteImport
      parentRoute: typeof DashboardProtectedPeriodsRoute
    }
    '/dashboard/_protected/periods/create': {
      id: '/dashboard/_protected/periods/create'
      path: '/create'
      fullPath: '/dashboard/periods/create'
      preLoaderRoute: typeof DashboardProtectedPeriodsCreateRouteImport
      parentRoute: typeof DashboardProtectedPeriodsRoute
    }
    '/dashboard/_protected/periods/_layout': {
      id: '/dashboard/_protected/periods/_layout'
      path: '/periods'
      fullPath: '/dashboard/periods'
      preLoaderRoute: typeof DashboardProtectedPeriodsLayoutRouteImport
      parentRoute: typeof DashboardProtectedPeriodsRoute
    }
    '/dashboard/_protected/periods/$periodId/tasks': {
      id: '/dashboard/_protected/periods/$periodId/tasks'
      path: '/tasks'
      fullPath: '/dashboard/periods/$periodId/tasks'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdTasksRouteImport
      parentRoute: typeof DashboardProtectedPeriodsPeriodIdRoute
    }
    '/dashboard/_protected/periods/$periodId/subjects': {
      id: '/dashboard/_protected/periods/$periodId/subjects'
      path: '/subjects'
      fullPath: '/dashboard/periods/$periodId/subjects'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsRouteImport
      parentRoute: typeof DashboardProtectedPeriodsPeriodIdRoute
    }
    '/dashboard/_protected/periods/$periodId/': {
      id: '/dashboard/_protected/periods/$periodId/'
      path: '/'
      fullPath: '/dashboard/periods/$periodId/'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdIndexRouteImport
      parentRoute: typeof DashboardProtectedPeriodsPeriodIdRoute
    }
    '/dashboard/_protected/periods/$periodId/settings': {
      id: '/dashboard/_protected/periods/$periodId/settings'
      path: '/settings'
      fullPath: '/dashboard/periods/$periodId/settings'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdSettingsRouteImport
      parentRoute: typeof DashboardProtectedPeriodsPeriodIdRoute
    }
    '/dashboard/_protected/periods/$periodId/_layout': {
      id: '/dashboard/_protected/periods/$periodId/_layout'
      path: '/$periodId'
      fullPath: '/dashboard/periods/$periodId'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdLayoutRouteImport
      parentRoute: typeof DashboardProtectedPeriodsPeriodIdRoute
    }
    '/dashboard/_protected/periods/$periodId/tasks/': {
      id: '/dashboard/_protected/periods/$periodId/tasks/'
      path: '/'
      fullPath: '/dashboard/periods/$periodId/tasks/'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdTasksIndexRouteImport
      parentRoute: typeof DashboardProtectedPeriodsPeriodIdTasksRoute
    }
    '/dashboard/_protected/periods/$periodId/subjects/': {
      id: '/dashboard/_protected/periods/$periodId/subjects/'
      path: '/'
      fullPath: '/dashboard/periods/$periodId/subjects/'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsIndexRouteImport
      parentRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsRoute
    }
    '/dashboard/_protected/periods/$periodId/tasks/kanban': {
      id: '/dashboard/_protected/periods/$periodId/tasks/kanban'
      path: '/kanban'
      fullPath: '/dashboard/periods/$periodId/tasks/kanban'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdTasksKanbanRouteImport
      parentRoute: typeof DashboardProtectedPeriodsPeriodIdTasksRoute
    }
    '/dashboard/_protected/periods/$periodId/tasks/create': {
      id: '/dashboard/_protected/periods/$periodId/tasks/create'
      path: '/create'
      fullPath: '/dashboard/periods/$periodId/tasks/create'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdTasksCreateRouteImport
      parentRoute: typeof DashboardProtectedPeriodsPeriodIdTasksRoute
    }
    '/dashboard/_protected/periods/$periodId/tasks/_layout': {
      id: '/dashboard/_protected/periods/$periodId/tasks/_layout'
      path: '/tasks'
      fullPath: '/dashboard/periods/$periodId/tasks'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdTasksLayoutRouteImport
      parentRoute: typeof DashboardProtectedPeriodsPeriodIdTasksRoute
    }
    '/dashboard/_protected/periods/$periodId/tasks/$taskId': {
      id: '/dashboard/_protected/periods/$periodId/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/dashboard/periods/$periodId/tasks/$taskId'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdTasksTaskIdRouteImport
      parentRoute: typeof DashboardProtectedPeriodsPeriodIdRoute
    }
    '/dashboard/_protected/periods/$periodId/subjects/create': {
      id: '/dashboard/_protected/periods/$periodId/subjects/create'
      path: '/create'
      fullPath: '/dashboard/periods/$periodId/subjects/create'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsCreateRouteImport
      parentRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsRoute
    }
    '/dashboard/_protected/periods/$periodId/subjects/_layout': {
      id: '/dashboard/_protected/periods/$periodId/subjects/_layout'
      path: '/subjects'
      fullPath: '/dashboard/periods/$periodId/subjects'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsLayoutRouteImport
      parentRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsRoute
    }
    '/dashboard/_protected/periods/$periodId/subjects/$subjectId': {
      id: '/dashboard/_protected/periods/$periodId/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/dashboard/periods/$periodId/subjects/$subjectId'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRouteImport
      parentRoute: typeof DashboardProtectedPeriodsPeriodIdRoute
    }
    '/dashboard/_protected/periods/$periodId/subjects/$subjectId/': {
      id: '/dashboard/_protected/periods/$periodId/subjects/$subjectId/'
      path: '/'
      fullPath: '/dashboard/periods/$periodId/subjects/$subjectId/'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdIndexRouteImport
      parentRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRoute
    }
    '/dashboard/_protected/periods/$periodId/subjects/$subjectId/tasks': {
      id: '/dashboard/_protected/periods/$periodId/subjects/$subjectId/tasks'
      path: '/tasks'
      fullPath: '/dashboard/periods/$periodId/subjects/$subjectId/tasks'
      preLoaderRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdTasksRouteImport
      parentRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRoute
    }
  }
}

interface DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRouteChildren {
  DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdTasksRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdTasksRoute
  DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdIndexRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdIndexRoute
}

const DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRouteChildren: DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRouteChildren =
  {
    DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdTasksRoute:
      DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdTasksRoute,
    DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdIndexRoute:
      DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdIndexRoute,
  }

const DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRouteWithChildren =
  DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRoute._addFileChildren(
    DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRouteChildren,
  )

interface DashboardProtectedPeriodsPeriodIdSubjectsRouteChildren {
  DashboardProtectedPeriodsPeriodIdSubjectsLayoutRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsLayoutRoute
  DashboardProtectedPeriodsPeriodIdSubjectsCreateRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsCreateRoute
  DashboardProtectedPeriodsPeriodIdSubjectsIndexRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsIndexRoute
}

const DashboardProtectedPeriodsPeriodIdSubjectsRouteChildren: DashboardProtectedPeriodsPeriodIdSubjectsRouteChildren =
  {
    DashboardProtectedPeriodsPeriodIdSubjectsLayoutRoute:
      DashboardProtectedPeriodsPeriodIdSubjectsLayoutRoute,
    DashboardProtectedPeriodsPeriodIdSubjectsCreateRoute:
      DashboardProtectedPeriodsPeriodIdSubjectsCreateRoute,
    DashboardProtectedPeriodsPeriodIdSubjectsIndexRoute:
      DashboardProtectedPeriodsPeriodIdSubjectsIndexRoute,
  }

const DashboardProtectedPeriodsPeriodIdSubjectsRouteWithChildren =
  DashboardProtectedPeriodsPeriodIdSubjectsRoute._addFileChildren(
    DashboardProtectedPeriodsPeriodIdSubjectsRouteChildren,
  )

interface DashboardProtectedPeriodsPeriodIdTasksRouteChildren {
  DashboardProtectedPeriodsPeriodIdTasksLayoutRoute: typeof DashboardProtectedPeriodsPeriodIdTasksLayoutRoute
  DashboardProtectedPeriodsPeriodIdTasksCreateRoute: typeof DashboardProtectedPeriodsPeriodIdTasksCreateRoute
  DashboardProtectedPeriodsPeriodIdTasksKanbanRoute: typeof DashboardProtectedPeriodsPeriodIdTasksKanbanRoute
  DashboardProtectedPeriodsPeriodIdTasksIndexRoute: typeof DashboardProtectedPeriodsPeriodIdTasksIndexRoute
}

const DashboardProtectedPeriodsPeriodIdTasksRouteChildren: DashboardProtectedPeriodsPeriodIdTasksRouteChildren =
  {
    DashboardProtectedPeriodsPeriodIdTasksLayoutRoute:
      DashboardProtectedPeriodsPeriodIdTasksLayoutRoute,
    DashboardProtectedPeriodsPeriodIdTasksCreateRoute:
      DashboardProtectedPeriodsPeriodIdTasksCreateRoute,
    DashboardProtectedPeriodsPeriodIdTasksKanbanRoute:
      DashboardProtectedPeriodsPeriodIdTasksKanbanRoute,
    DashboardProtectedPeriodsPeriodIdTasksIndexRoute:
      DashboardProtectedPeriodsPeriodIdTasksIndexRoute,
  }

const DashboardProtectedPeriodsPeriodIdTasksRouteWithChildren =
  DashboardProtectedPeriodsPeriodIdTasksRoute._addFileChildren(
    DashboardProtectedPeriodsPeriodIdTasksRouteChildren,
  )

interface DashboardProtectedPeriodsPeriodIdRouteChildren {
  DashboardProtectedPeriodsPeriodIdLayoutRoute: typeof DashboardProtectedPeriodsPeriodIdLayoutRoute
  DashboardProtectedPeriodsPeriodIdSettingsRoute: typeof DashboardProtectedPeriodsPeriodIdSettingsRoute
  DashboardProtectedPeriodsPeriodIdIndexRoute: typeof DashboardProtectedPeriodsPeriodIdIndexRoute
  DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRouteWithChildren
  DashboardProtectedPeriodsPeriodIdSubjectsRoute: typeof DashboardProtectedPeriodsPeriodIdSubjectsRouteWithChildren
  DashboardProtectedPeriodsPeriodIdTasksTaskIdRoute: typeof DashboardProtectedPeriodsPeriodIdTasksTaskIdRoute
  DashboardProtectedPeriodsPeriodIdTasksRoute: typeof DashboardProtectedPeriodsPeriodIdTasksRouteWithChildren
}

const DashboardProtectedPeriodsPeriodIdRouteChildren: DashboardProtectedPeriodsPeriodIdRouteChildren =
  {
    DashboardProtectedPeriodsPeriodIdLayoutRoute:
      DashboardProtectedPeriodsPeriodIdLayoutRoute,
    DashboardProtectedPeriodsPeriodIdSettingsRoute:
      DashboardProtectedPeriodsPeriodIdSettingsRoute,
    DashboardProtectedPeriodsPeriodIdIndexRoute:
      DashboardProtectedPeriodsPeriodIdIndexRoute,
    DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRoute:
      DashboardProtectedPeriodsPeriodIdSubjectsSubjectIdRouteWithChildren,
    DashboardProtectedPeriodsPeriodIdSubjectsRoute:
      DashboardProtectedPeriodsPeriodIdSubjectsRouteWithChildren,
    DashboardProtectedPeriodsPeriodIdTasksTaskIdRoute:
      DashboardProtectedPeriodsPeriodIdTasksTaskIdRoute,
    DashboardProtectedPeriodsPeriodIdTasksRoute:
      DashboardProtectedPeriodsPeriodIdTasksRouteWithChildren,
  }

const DashboardProtectedPeriodsPeriodIdRouteWithChildren =
  DashboardProtectedPeriodsPeriodIdRoute._addFileChildren(
    DashboardProtectedPeriodsPeriodIdRouteChildren,
  )

interface DashboardProtectedPeriodsRouteChildren {
  DashboardProtectedPeriodsLayoutRoute: typeof DashboardProtectedPeriodsLayoutRoute
  DashboardProtectedPeriodsCreateRoute: typeof DashboardProtectedPeriodsCreateRoute
  DashboardProtectedPeriodsIndexRoute: typeof DashboardProtectedPeriodsIndexRoute
  DashboardProtectedPeriodsPeriodIdRoute: typeof DashboardProtectedPeriodsPeriodIdRouteWithChildren
}

const DashboardProtectedPeriodsRouteChildren: DashboardProtectedPeriodsRouteChildren =
  {
    DashboardProtectedPeriodsLayoutRoute: DashboardProtectedPeriodsLayoutRoute,
    DashboardProtectedPeriodsCreateRoute: DashboardProtectedPeriodsCreateRoute,
    DashboardProtectedPeriodsIndexRoute: DashboardProtectedPeriodsIndexRoute,
    DashboardProtectedPeriodsPeriodIdRoute:
      DashboardProtectedPeriodsPeriodIdRouteWithChildren,
  }

const DashboardProtectedPeriodsRouteWithChildren =
  DashboardProtectedPeriodsRoute._addFileChildren(
    DashboardProtectedPeriodsRouteChildren,
  )

interface DashboardProtectedRouteRouteChildren {
  DashboardProtectedIndexRoute: typeof DashboardProtectedIndexRoute
  DashboardProtectedPeriodsRoute: typeof DashboardProtectedPeriodsRouteWithChildren
}

const DashboardProtectedRouteRouteChildren: DashboardProtectedRouteRouteChildren =
  {
    DashboardProtectedIndexRoute: DashboardProtectedIndexRoute,
    DashboardProtectedPeriodsRoute: DashboardProtectedPeriodsRouteWithChildren,
  }

const DashboardProtectedRouteRouteWithChildren =
  DashboardProtectedRouteRoute._addFileChildren(
    DashboardProtectedRouteRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardProtectedRouteRoute: typeof DashboardProtectedRouteRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProtectedRouteRoute: DashboardProtectedRouteRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  LayoutRoute: LayoutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
